-- create table employee_details(
-- EmployeeID int primary key ,
-- FirstName varchar ,
-- LastName varchar ,
-- Department varchar,
-- City varchar ,
-- ManagerID int ,
-- Salary int
-- )

-- copy employee_details from'D:\SQL Task-3\employee_details.csv' delimiter ',' csv header

-- create table customer_details(
-- customer_id varchar primary key ,
-- customer_name varchar ,
-- age int check ( age >18 and age <50),
-- contact_number numeric(10,0) unique ,
-- email varchar not null ,
-- pancard_no varchar(10) unique not null,
-- aadhaar_card_no numeric (12,0) not null , 
-- area varchar ,
-- city varchar ,
-- state varchar ,
-- zipcode numeric (6,0)
-- )
-- drop table customer_details
-- select * from customer_details
-- copy customer_details from'D:/SQL Task-3/customer_details.csv' delimiter ',' csv header

-- create table order_details(
-- order_id varchar primary key ,
-- order_date date ,
-- customer_id varchar references customer_details( customer_id),
-- order_status varchar ,
-- payment_mode varchar ,
-- total_amount bigint
-- )
-- select * from order_details
-- copy order_details from'D:/SQL Task-3/order_details.csv' delimiter ',' csv header

-- create table product_details(
-- product_id varchar primary key,
-- product_name varchar ,
-- category varchar,
-- price_inr int 
-- )
-- select * from product_details

-- create table sale_details(
-- sale_id varchar primary key ,
-- order_id varchar references order_details(order_id),
-- product_id varchar references product_details (product_id),
-- quantity_sold int ,
-- unit_price int ,
-- discount_pct numeric (3,2),
-- tax_pct numeric (3,2),
-- line_total int ,
-- delivery_date date 
-- )
-- select * from sale_details

-- select * from customer_details c join order_details o on c.customer_id = o.customer_id
-- join sale_details s on s.order_id = o.order_id 
-- join product_details p on p.product_id = s.product_id

-- 2. CUSTOMER & ORDER FILTERING
-- Tasks
-- 1. Retrieve all orders placed by customers from Mumbai or Pune.
 -- select * from order_details where customer_id in(select customer_id from customer_details where city in('Mumbai' ,'Pune'))

-- 2. Identify premium products priced between ₹5,000 and ₹50,000 for targeted
-- promotions.
-- select * from product_details where price_inr between 5000 and 50000

-- 3. Find customers residing in Mumbai, Nagpur, or Pune for regional marketing
-- campaigns.
-- select * from customer_details where city in('Mumbai' ,'Pune' ,'Nagpur')

-- 4. Fetch all Delivered orders paid via UPI to evaluate digital payment success.
-- select * from order_details where payment_mode = 'UPI' and  order_status = 'Delivered'


-- 3. DATA CORRECTION & STANDARDIZATION  
-- Tasks

-- 1. Cancel orders with total_amount < 500 as per company policy. ****
-- select * from order_details where total_amount < 500

-- 2. Increase salaries by 10% for employees in HR after annual appraisal.
-- select * from employee_details

-- update employee_details
-- set salary = salary * 1.10 
-- where department = 'HR Manager'


-- 3. Standardize customer city as Mumbai for all customers from Andheri areas.
-- select * from customer_details where area ilike '%Andheri%'

-- 4. Reclassify laptop products under the Electronics category.
-- select product_name from product_details where product_name ilike '%laptop%'

-- 5. Migrate employee email domains from gmail to official @company.com
-- alter table employee_details
-- rename email to gmail


-- 4. BUSINESS KPIs & AGGREGATION
-- Tasks
-- 1. Calculate total revenue generated by the company.
-- select * from sale_details
-- select sum(quantity_sold * unit_price) as total_revenue from sale_details

-- 2. Compute average salary per department for budget planning
-- select department , avg(salary) from employee_details group by department 

-- 3. Count total orders by order status to assess fulfillment efficiency.
-- select count(*) filter (where order_status = 'Shipped') as shipped_order,
--  count(*) filter (where order_status = 'Delivered') as Delivered,
--  count(*) filter (where order_status ='Placed') as Placed,
--  count(*) filter (where order_status = 'Cancelled') as cancelled
-- from order_details 


-- 4. Identify highest and lowest priced products per category.
-- select category , max(price_inr) as max_price , min(price_inr) as min_price from product_details group by category

-- 5. Calculate total quantity sold per product to understand demand trends.
-- select  p.product_id , sum(quantity_sold) from  sale_details s 
-- join product_details p on s.product_id = p.product_id group by p.product_id




-- 5. RANKING & PAGINATION
-- Tasks
-- 1. List the top 5 most expensive products.
-- select * from product_details order by price_inr desc limit 5

-- 2. Retrieve the 3 most recent orders for daily monitoring.
-- select * from order_details order by order_date desc limit 3

-- 3. Identify all unique customer cities to assess market reach.
-- select distinct city from customer_details 

-- 4. Rank customers by total lifetime spending and show top 10.
-- select * from 
-- (select c.customer_id , c.customer_name  ,o.total_amount, c.age,
-- dense_rank() over (order by total_amount desc) as ranking_top
-- from customer_details c join order_details o on c.customer_id = o.customer_id  
-- ) t 
-- where  ranking_top <= 10

-- 5. Paginate order history by skipping first 5 records and fetching next 5.
-- select * from order_details limit 5 offset 5

-- 6. TEXT PROCESSING
-- Tasks
-- 1. Convert customer names to uppercase.
-- select upper(customer_name )from customer_details

-- 2. Extract short product codes from product names.***
-- select * from product_details where ilike 

-- 3. Display employee full names by concatenating first and last names.

-- 4. Measure character length of customer names for UI validation.
-- select length(customer_name )from customer_details


-- 5. Replace spaces with underscores in product names for system compatibility.
-- select product_name , replace (product_name ,' ' , '_'  )from product_details


-- 7. DATE & TIME ANALYSIS
-- Tasks
-- 1. Extract year and month from order dates for trend analysis.
-- select order_date , extract (month from order_date ) as order_month , 
-- extract(year from order_date) as order_year from order_details

-- 2. Calculate days between consecutive orders to understand purchase frequency. 
-- select order_date , 
-- order_date - lead(order_date) over(order by order_date) 
-- from order_details 

-- 3. Display system date and timestamp for audit logs.
-- select current_date
-- select current_timestamp

-- 4. Identify all orders placed in September 2024.
-- select * from order_details where extract ( month from order_date) = 9 and extract (year from order_date) = 2024


-- 5. Estimate expected delivery date by adding 7 days to order date.
-- select order_date , order_date + interval '7 days' as adding from order_details 


